var mongoose = require("mongoose");
var Schema = mongoose.Schema;


var PlayerSchema = new Schema({
    name:{
        type:String,
        required:true
    },
    role:{
        iswicketKeeper:{
            type:Number,
            required:true
        },
        isCaptain:{
            type:Number,
            required:true
        },
        isBatsmen:{
            type:Number,
            required:true
        },
        isBowler:{
            type:Number,
            required:true            
        }
    },
    team:{
        type:String,
        required:true
    },
    nationality:{
        type:String,
        required:true
    },
    playerValue:{
        type:Number,
        required:true
    },
    career:{
        matches:{
            type:String,
            required:true
        },
        inningsPlayed:{
            type:String,
            required:true
        },
        notOut:{
            type:String,
            required:true
        },
        runsScored:{
            type:String,
            required:true
        },
        highestScore:{
            type:String,
            required:true
        },
        battingAverage:{
            type:String,
            required:true
        },
        ballsFaced:{
            type:String,
            required:true
        },
        strikeRate:{
            type:String,
            required:true
        },
        hundreadRuns:{
            type:String,
            required:true
        },
        fiftyRuns:{
            type:String,
            required:true
        },
        fourRunsOverall:{
            type:String,
            required:true
        },
        sixRunsOverall:{
            type:String,
            required:true
        },
        catchesPerMatch:{
            type:String,
            required:true
        },
        catchesTaken:{
            type:String,
            required:true
        },
        matchesPlayed:{
            type:String,
            required:true
        },
        inningsPlayed:{
            type:String,
            required:true
        },
        ballsBowled:{
            type:String,
            required:true
        },
        runsGiven:{
            type:String,
            required:true
        },
        wicketsTaken:{
            type:String,
            required:true
        },
        ballingEconomy:{
            type:String,
            required:true
        },
        fiveWicketsHaul:{
            type:String,
            required:true
        }
    }

});

const Player = module.exports = mongoose.model('Player',PlayerSchema)